runtime: nodejs16

env_variables:
  NODE_ENV: production

handlers:
  - url: /(.*\.(gif|png|jpg|ico|js|css|woff2|woff|ttf|svg|eot|map))$
    static_files: dist/\1
    upload: dist/.*\.(gif|png|jpg|ico|js|css|woff2|woff|ttf|svg|eot|map)$
    http_headers:
      Cache-Control: "public, max-age=31536000"
  - url: /.*
    script: auto
