runtime: nodejs16  # Sesuaikan dengan versi Node.js yang dibutuhkan

env_variables:
  NODE_ENV: production

# Sesuaikan dengan skrip build di package.json
build_commands:
  - npm install
  - npm run build

# Sesuaikan dengan port yang digunakan aplikasi
handlers:
- url: /.*
  script: auto
  secure: always  # Paksa HTTPS untuk keamanan
